### ISSUE TITLE
Doesn't compile with latest version of Beego

### ISSUE THREAD

**Issue by nathan-osman** [oal/beego-pongo2#7]
Running:

    go get -u github.com/oal/beego-pongo2

...results in the following errors:

    beego-pongo2/main.go:55: undefined: beego.XSRFKEY
    beego-pongo2/main.go:78: undefined: beego.FlashName
    beego-pongo2/main.go:83: undefined: beego.FlashSeperator
    beego-pongo2/main.go:90: undefined: beego.FlashName
    beego-pongo2/main.go:97: undefined: beego.AutoRender
    beego-pongo2/tags_urlfor.go:29: undefined: beego.UrlFor
    beego-pongo2/tags_xsrftoken.go:15: undefined: beego.EnableXSRF

A number of these variables have moved from `beego` to `beego.BConfig.WebConfig`.

**Comment by apung** [comment]
I have submited pull request with changes above. Please see my forked repo at https://github.com/apung/beego-pongo2

**Comment by apung** [comment]
https://github.com/apung/beego-pongo2/commit/f747b47563cd819ba9b9858d55ffa61edbcbd717

**Comment by oal** [comment]
@apung's changes have been merged. I don't use Beego myself at the moment, so I apologize for not having kept this library up to date. Happy to merge PRs for future changes, if needed. :+1:
